config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Defines the root path route ("/")
  root "static_pages#home"

  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  normalizes :email, with: -> email { email.downcase }

  has_secure_password

  attr_accessor :remember_token

  def self.digest(str)
    BCrypt::Password.create(str, cost: BCrypt::Engine.cost)
  end

  def remember
    self.remember_token = SecureRandom.urlsafe_base64
    remember_digest = self.class.digest(remember_token)
    update_attribute(:remember_digest, remember_digest)
    remember_digest
  end

  def authenticated?(remember_token)
    remember_digest &&
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def session_token
    remember_digest || remember
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def log_in(user)
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    return @current_user if @current_user

    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      if user && session[:session_token] == user.session_token
        @current_user = user
      end
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in(user)
      redirect_to forwarding_url || user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out if current_user
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in(@user)
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def logged_in_user
    return if current_user

    store_location
    flash[:danger] = "Please log in."
    redirect_to login_url, status: :see_other
  end

  def correct_user
    redirect_to(root_url, status: :see_other) unless params[:id].to_i == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <p class="col-md-4 mb-0 text-body-secondary">The <a href="https://railstutorial.jp/" class="text-body-secondary">Ruby on Rails Tutorial</a> by <a href="https://www.michaelhartl.com/" class="text-body-secondary">Michael Hartl</a></p>

  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item"><%= link_to 'About', about_path, class: "nav-link px-2 text-body-secondary" %></li>
    <li class="nav-item"><%= link_to 'Contact', contact_path, class: "nav-link px-2 text-body-secondary" %></li>
    <li class="nav-item"><a href="https://news.railstutorial.org/" class="nav-link px-2 text-body-secondary">News</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <%= link_to 'Sample App', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Help', help_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
          <li class="nav-item dropdown">
            <%= link_to 'Account', '#', class: 'nav-link dropdown-toggle', 'data-bs-toggle': 'dropdown' %>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to "Profile", current_user, class: 'dropdown-item' %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Log out", logout_path,
                                       data: { "turbo-method": :delete }, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      <%= debug(current_user.as_json) if Rails.env.development? %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/screencast">screencast</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="bg-body-tertiary p-5 rounded">
  <h1>Sample App</h1>
  <p class="lead">This is the home page for the <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a> sample application.</p>
  <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model:) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :email, class: 'form-label' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :password, class: 'form-label' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :password_confirmation, class: 'form-label' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit button_text, class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <h1>Update your profile</h1>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
    <%= render 'form', button_text: 'Save changes', model: @user %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <h1>All Users</h1>
    <%= will_paginate renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <div class="users">
      <% @users.each do |user| %>
        <div class="border-bottom m-2 p-2">
          <%= gravatar_for user, size: 50 %>
          <%= link_to user.name, user %>
        </div>
      <% end %>
    </div>
    <%= will_paginate renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <p>This will be a signup page for new users.</p>
    <%= render 'form', button_text: 'Create my account', model: @user %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="column col-lg-3">
    <h3>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h3>
  </div>
  <div class="side col-lg-9">
  </div>
</div>